# .github/workflows/wiki.yml
name: Publish Wiki

on:
  push:
    branches: [main]
    paths: ['wiki/**']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Push to wiki
        run: |
          cp -r wiki/ wiki-temp/
          cd wiki-temp
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update wiki"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git main
